"""empty message

Revision ID: 4a4129edf566
Revises: 
Create Date: 2019-04-18 20:29:01.621787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a4129edf566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', mysql.DOUBLE(precision=15, scale=8, asdecimal=True), nullable=False),
    sa.Column('price', mysql.DOUBLE(precision=15, scale=8, asdecimal=True), nullable=True),
    sa.Column('final_amount', mysql.DOUBLE(precision=15, scale=8, asdecimal=True), nullable=True),
    sa.Column('requested_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
